### ISSUE TITLE
EntryPoint.runBenchmark is not a function

### ISSUE THREAD

**Issue by MaxGraey** [nischayv/as-benchmarks#2]
Hi. Really interesting bench suite but unfortunately something wrong with build process. After build AS, `npm run start:prod` and launch run button I got `EntryPoint.runBenchmark is not as function`

**Comment by nischayv** [comment]
That should be fixed now, accidentally forgot to export the function and broke it while doing some code cleanup!

**Comment by nischayv** [comment]
Also just a heads up, the tests do take a while to run right now, roughly 10 mins or so. Eventually I'll add options on the web page or command line to run the tests on smaller inputs.

**Comment by MaxGraey** [comment]
Got it!
