### ISSUE TITLE
Create UI to run benchmarks with user selected options

### ISSUE THREAD

**Issue by nischayv** [nischayv/as-benchmarks#3]

**Comment by MaxGraey** [comment]
It will be great has "Run All Tests" in selection list

**Comment by MaxGraey** [comment]
And I guess `120` iterations as default is too much. Probably `30` will be better?

**Comment by nischayv** [comment]
I chose `120` based on the Jetstream 2 benchmark (https://browserbench.org/JetStream/in-depth.html). For example, like in the images below, stuff like garbage collection happens periodically (the possible reason for the spikes in js). So `120` was the recommended number to see how the function behaves over multiple iterations. But I also know `120` is quite a lot given each test takes a while, so I don't mind if we change it either!

Also, thanks for the interest in this project!!

![pagerank-firefox](https://user-images.githubusercontent.com/13353147/80922452-10ebee00-8d32-11ea-8099-d13c87c26b7f.png)
![lud-firefox](https://user-images.githubusercontent.com/13353147/80922503-7049fe00-8d32-11ea-9f70-650658021c21.png)

**Comment by MaxGraey** [comment]
I see

**Comment by nischayv** [comment]
Already addressed by #6
